name: Merge
on:
  push:
    branches:
      - main

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_CLI_ARGS: -no-color
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VER }}

      - name: Terraform Init
        run: terraform init
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  content:
    runs-on: ubuntu-latest
    needs: infrastructure
    steps:
      - uses: actions/checkout@v2

      - name: Group relevant files into src
        run: |
          mkdir src
          cp *.css src/
          cp *.html src/
          cp *.png src/
          ls src

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files to storage account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.11.1
          inlineScript: az storage blob sync --source src --container '$web' --account-name websitesdomroutley
